const helpTopics = [
  { id: 'help-roles', label: 'Roles' },
  { id: 'help-naming-idiom', label: 'Naming idiom' },
  { id: 'help-generation', label: 'Generation & reroll' },
  { id: 'help-audition', label: 'Browser audition' },
  { id: 'help-locking', label: 'Locking' },
  { id: 'help-components', label: 'Identity components' },
] as const;

export function HelpView() {
  return (
    <section className="help-view panel" aria-labelledby="help-title">
      <div className="help-heading">
        <p className="eyebrow">Help</p>
        <h1 id="help-title">Using Name Forge</h1>
        <p>
          Most controls should explain themselves. This guide covers the few concepts where a short label is not enough.
        </p>
      </div>

      <nav className="help-topic-nav" aria-label="Help topics">
        {helpTopics.map((topic) => <a key={topic.id} href={`#${topic.id}`}>{topic.label}</a>)}
      </nav>

      <div className="help-sections">
        <section id="help-roles" className="help-section" aria-labelledby="help-roles-title">
          <h2 id="help-roles-title">Roles and generation influence</h2>
          <p>
            Roles add story context to cast members. <strong>Generation influence</strong> controls how much an assigned role changes
            the generated name. With influence off, the role is context only.
          </p>
          <p>
            See <strong>Configure → Roles → Role guide</strong> for the creative direction behind each role. Those directions are
            fictional prompts, not claims that real people or story roles inherently sound a certain way.
          </p>
        </section>

        <section id="help-naming-idiom" className="help-section" aria-labelledby="help-naming-idiom-title">
          <h2 id="help-naming-idiom-title">Naming idiom</h2>
          <p>
            A Naming idiom shapes the characteristic sound and form of generated names. Your other settings still apply
            independently.
          </p>
          <p>
            There is no separate adherence or strength setting for an idiom. It describes a creative direction, not cultural
            authenticity.
          </p>
        </section>

        <section id="help-generation" className="help-section" aria-labelledby="help-generation-title">
          <h2 id="help-generation-title">Deterministic generation and reroll</h2>
          <p>
            The same settings and seed produce the same result. <strong>Start cast</strong> and <strong>Generate</strong> choose a
            fresh seed so you get a new result.
          </p>
          <p>
            Enter a Generation seed when you want to reproduce a result. Rerolling one selected, unlocked name gives that slot a
            new result while preserving the rest of the cast.
          </p>
        </section>

        <section id="help-audition" className="help-section" aria-labelledby="help-audition-title">
          <h2 id="help-audition-title">Browser audition and pronunciation</h2>
          <p>
            Browser playback is an approximate voice draft. It can help you hear a possible reading, but your browser's speech
            engine may pronounce an invented name differently from Name Forge's sound guide.
          </p>
          <p>
            The sound guide shows the intended reading generated by Name Forge. Neither it nor browser playback is a claim that
            every person, accent, or speech system will pronounce the name the same way.
          </p>
        </section>

        <section id="help-locking" className="help-section" aria-labelledby="help-locking-title">
          <h2 id="help-locking-title">Locking names</h2>
          <p>
            Locked names stay in place when you generate again. An unlocked name can be rerolled on its own.
          </p>
          <p>
            If you change a setting that would change a locked name, Name Forge unlocks it rather than pretending the old name
            matches the new settings.
          </p>
        </section>

        <section id="help-components" className="help-section" aria-labelledby="help-components-title">
          <h2 id="help-components-title">Identity components</h2>
          <p>
            Some parts of a Fiction Cast identity are generated names and have their own sound and spelling details. You can inspect
            those generated parts separately.
          </p>
          <p>
            Other parts—such as titles, epithets, initials, and particles—may be selected or assembled by Fiction Cast. Seeing one
            in the full identity does not mean every part was independently generated.
          </p>
        </section>
      </div>
    </section>
  );
}
