import { describe, expect, it } from 'vitest';
import { renderToString } from 'react-dom/server';
import App from './App';

describe('App', () => {
  it('renders the generation shell with grouped controls, nested card details, compact exports, and project chrome', () => {
    const html = renderToString(<App />);

    expect(html).toContain('Name Forge');
    expect(html).toContain('Generator');
    expect(html).toContain('Changelog');
    expect(html).toContain('About');
    expect(html).toContain('Basics');
    expect(html).toContain('Fiction');
    expect(html).toContain('Rarity');
    expect(html).toContain('Cast size');
    expect(html).toContain('Decrease cast size');
    expect(html).toContain('Increase cast size');
    expect(html).toContain('Style preset');
    expect(html).toContain('Name format');
    expect(html).toContain('Mixed cast formats');
    expect(html).toContain('Initials + family');
    expect(html).toContain('Title + name');
    expect(html).toContain('Epithet/place-style');
    expect(html).toContain('Cast role mix');
    expect(html).toContain('Role influence');
    expect(html).toContain('Off');
    expect(html).toContain('Light');
    expect(html).toContain('Strong');
    expect(html).toContain('Roles label cast slots only; generation and scoring stay role-neutral.');
    expect(html).toContain('Role influence is opt-in.');
    expect(html).toContain('sound patterns');
    expect(html).toContain('Choose a role mix to reveal optional slot-by-slot overrides.');
    expect(html).toContain('Novelty value');
    expect(html).toContain('Randomize Novelty');
    expect(html).toContain('Randomize sliders');
    expect(html).toContain('Randomize seed');
    expect(html).toContain('Generate cast');
    expect(html).toContain('Ensemble balance');
    expect(html).toContain('Export cast');
    expect(html).toContain('JSON');
    expect(html).toContain('Markdown');
    expect(html).toContain('Copy JSON');
    expect(html).toContain('Copy Markdown');
    expect(html).toContain('Show Markdown preview');
    expect(html).toContain('# Name Forge Cast Export');
    expect(html).toContain('Role influence: off');
    expect(html).toContain('name-forge-001');
    expect(html).toContain('<details');
    expect(html).toContain('texture-');
    expect(html).toContain('Open');
    expect(html).toContain('Details');
    expect(html).toContain('Texture');
    expect(html).toContain('Fit scores');
    expect(html).toContain('Name parts');
    expect(html).toContain('fit score breakdown');
    expect(html).not.toContain('Card detail');
    expect(html).not.toContain('Brief');
    expect(html).not.toContain('Tone');
    expect(html).not.toContain('Diagnostics');
    expect(html).not.toContain('diagnostic score breakdown');
    expect(html).not.toContain('Alternate spellings</h3>');
    expect(html).not.toContain('No alternate spellings for this name.');
    expect(html).not.toContain('Download JSON');
    expect(html).not.toContain('Download Markdown');
    expect(html).not.toContain('Export generated cast');
    expect(html).not.toContain('Source trace');
    expect(html).not.toContain('Overall fit score');
    expect(html).not.toContain('medium target');
    expect(html).not.toContain('rarity target');
    expect(html).not.toContain('Generated from the same base name');
    expect(html).not.toContain('Errata');
    expect(html).not.toContain('Unreleased');
    expect(html).not.toContain('Name Forge version');
  });
});
